'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const styles=[['modern','Modern','Light, spacious and welcoming.'],['classic','School','A structured school-style workspace.'],['focus','Focus','A calm, lesson-first experience.']];
let state={style:'modern',colour:'#395ea5',brand:'Noor Academy',domain:'portal.nooracademy.co.uk',mode:'solo',role:'teacher',page:'overview',selected:'s1',students:[],homework:[],activity:[]};
function samples(){state.students=[{id:'s1',name:'Yusuf Ahmed',parent:'Amina Ahmed',group:'Qaidah Foundations',attendance:'Not recorded',points:85},{id:'s2',name:'Maryam Ali',parent:'Sara Ali',group:'Qaidah Foundations',attendance:'Present',points:120},{id:'s3',name:'Adam Hassan',parent:'Omar Hassan',group:'Qur’an Reading',attendance:'Present',points:65}];state.homework=[{id:'h1',title:'Practise joined letters',text:'Read the joined letters slowly. Practise for five minutes before your next lesson.',due:'2026-10-12',group:'Qaidah Foundations',done:[]}];state.activity=['Your sample portal is ready.'];state.selected='s1';}
const initials=n=>n.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function log(t){state.activity.unshift(t);state.activity=state.activity.slice(0,8);toast(t)}
function pupil(){return state.students.find(s=>s.id===state.selected)||state.students[0]}
function staff(){return ['teacher','admin'].includes(state.role)}
function picker(label,values,action,id){return `<details class="picker"><summary aria-label="${esc(action==='attendance'?'Attendance for '+state.students.find(s=>s.id===id)?.name:action)}">${esc(label)}</summary><div class="choices">${values.map(v=>`<button type="button" data-action="${action}" data-id="${esc(id||'')}" data-value="${esc(v)}">${esc(v)}</button>`).join('')}</div></details>`}
function person(s){return `<div class="person"><span class="avatar">${esc(initials(s.name))}</span><div><strong>${esc(s.name)}</strong><small>${esc(s.group)}</small></div></div>`}
function heading(title,sub,action=''){return `<div class="page-heading"><div><span class="eyebrow">${esc(state.role==='admin'?'MANAGEMENT':state.role.toUpperCase()+' PORTAL')}</span><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function hwCard(h,s){const done=s&&h.done.includes(s.id);return `<article class="card"><div class="card-head"><span class="pill">${esc(h.group)}</span><small>Due ${esc(h.due)}</small></div><h3>${esc(h.title)}</h3><p style="white-space:pre-wrap">${esc(h.text)}</p>${state.role==='student'?`<button data-action="complete" data-id="${h.id}" ${done?'disabled':''}>${done?'✓ Completed':'Mark practice complete'}</button>`:state.role==='parent'?`<span class="pill">${done?'✓ Practice completed':'Practice to do'}</span>`:`<small>${h.done.length} completed · ${state.students.filter(s=>s.group===h.group).length} assigned</small>`}</article>`}
function content(){const s=pupil(),isStaff=staff();const list=isStaff?state.students:[s];const homework=isStaff?state.homework:state.homework.filter(h=>h.group===s.group);const roleSub=isStaff?'A clear picture of your teaching day.':state.role==='parent'?`A little closer to ${esc(s.name.split(' ')[0])}’s learning.`:'Your next step starts here.';
if(state.page==='overview')return heading(isStaff?'Good afternoon.':state.role==='parent'?`${esc(s.parent)}’s family`:`Assalamu alaikum, ${esc(s.name.split(' ')[0])}.`,roleSub,isStaff?'<div class="actions"><button class="primary" data-action="homework-dialog">Assign homework +</button></div>':'')+`<div class="stats"><div class="stat"><strong>${isStaff?state.students.length:s.points}</strong><span>${isStaff?'Pupils':'Learning points'}</span></div><div class="stat"><strong>${isStaff?new Set(state.students.map(s=>s.group)).size:homework.filter(h=>!h.done.includes(s.id)).length}</strong><span>${isStaff?'Classes':'Practice to do'}</span></div><div class="stat"><strong>${isStaff?state.students.filter(s=>s.attendance==='Present').length:esc(s.attendance)}</strong><span>${isStaff?'Present today':'Today’s attendance'}</span></div></div><div class="grid"><div><article class="card accent"><span class="eyebrow" style="color:inherit">YOUR NEXT LESSON</span><h2 style="margin-top:15px">${esc(isStaff?'Qaidah Foundations':s.group)}</h2><p>Monday · 16:30–17:30</p><button data-action="page" data-value="${isStaff?'attendance':'homework'}">${isStaff?'Open the register':'See my practice'} →</button></article><article class="card"><h3>${isStaff?'Your pupils':'Learning progress'}</h3>${isStaff?state.students.slice(0,3).map(x=>`<div class="student-row">${person(x)}<span class="pill">${x.points} points</span></div>`).join(''):`<p>Building confidence with each lesson.</p><div class="progress"><i></i></div><p class="hint" style="margin-top:12px">Illustrative learning progress · chapter 4 of 6</p>`}</article></div><div><article class="card"><h3>${isStaff?'Recent activity':'Latest practice'}</h3>${isStaff?state.activity.map(a=>`<div class="feed">${esc(a)}<small>This demo session</small></div>`).join(''):homework.length?homework.slice(-1).map(h=>`<h3>${esc(h.title)}</h3><p>${esc(h.text)}</p><button data-action="page" data-value="homework">Open homework →</button>`).join(''):'<p>No practice assigned yet.</p>'}</article><article class="card"><h3>${isStaff?'Try a different perspective.':'Connected to your teacher.'}</h3><p>${isStaff?'Assign practice, then switch to a pupil or parent. Their view updates immediately.':'Lesson records and practice come together in one place.'}</p>${isStaff?'<button data-action="role" data-value="parent">View as a parent →</button>':''}</article></div></div>`;
if(state.page==='students'&&isStaff)return heading('Every learner, known.','Sample pupils and the people supporting them.','<div class="actions"><button data-action="import-dialog">Import sample CSV</button><button class="primary" data-action="student-dialog">Add sample pupil +</button></div>')+`<article class="card">${state.students.map(s=>`<div class="student-row">${person(s)}<div><small>Parent: ${esc(s.parent)}</small><div class="actions"><span class="pill">${s.points} points</span><button data-action="points" data-id="${s.id}">+5 points</button><button data-action="preview-pupil" data-id="${s.id}">Student view →</button></div></div></div>`).join('')}</article>`;
if(state.page==='attendance'&&isStaff)return heading('A good start to class.','Record attendance and see it update in family views.','<div class="actions"><button data-action="all-present">Mark all present</button></div>')+`<article class="card">${state.students.map(s=>`<div class="student-row">${person(s)}${picker(s.attendance,['Not recorded','Present','Late','Absent'],'attendance',s.id)}</div>`).join('')}</article>`;
if(state.page==='homework')return heading(isStaff?'A little practice. Real progress.':'Your practice, all here.',isStaff?'Assign a task to a class. Families see it immediately.':'Small steps between lessons.',isStaff?'<div class="actions"><button class="primary" data-action="homework-dialog">Assign homework +</button></div>':'')+homework.map(h=>hwCard(h,s)).join('');
if(state.page==='classes')return heading('Room to learn.','Your sample timetable.')+[...new Set(list.map(s=>s.group))].map(g=>`<article class="card"><span class="pill">MONDAY · 16:30–17:30</span><h2 style="margin-top:15px">${esc(g)}</h2><p>${isStaff?state.students.filter(s=>s.group===g).length+' pupils':'Your weekly lesson'} · Online classroom</p><button data-action="page" data-value="${isStaff?'attendance':'homework'}">${isStaff?'Take attendance':'View practice'} →</button></article>`).join('');
if(state.page==='reports'&&isStaff)return heading('Your teaching at a glance.','A simple summary of this sample session.')+`<article class="card">${state.students.map(s=>`<div class="student-row">${person(s)}<span>${esc(s.attendance)} · ${s.points} points</span></div>`).join('')}<p class="hint">The HTML export includes the currently visible view and its fictional records.</p><button data-action="export">Export this view</button></article>`;
return heading('My progress','A record of your learning.')+`<article class="card"><h2>${esc(s.name)}</h2><p>${esc(s.group)}</p><div class="stats"><div class="stat"><strong>${s.points}</strong><span>Points</span></div><div class="stat"><strong>${homework.filter(h=>h.done.includes(s.id)).length}</strong><span>Completed tasks</span></div></div><p>Today’s attendance: ${esc(s.attendance)}</p></article>`;
}
function render(){document.body.dataset.style=state.style;document.body.style.setProperty('--accent',state.colour);document.body.style.setProperty('--tint',state.colour+'12');const roles=state.mode==='solo'?['teacher','student','parent']:['admin','teacher','student','parent'];const pages=staff()?['overview','classes','students','attendance','homework',...(state.role==='admin'||state.mode==='solo'?['reports']:[])]:['overview','classes','homework','progress'];if(!pages.includes(state.page))state.page='overview';$('#workspace').innerHTML=`<div class="portal"><header class="portal-header"><div class="portal-brand"><span class="monogram">${esc(initials(state.brand))}</span><div>${esc(state.brand)}<small class="domain">${esc(state.domain)} · preview</small></div></div><div class="role-strip" aria-label="Sample role">${roles.map(r=>`<button data-action="role" data-value="${r}" class="${r===state.role?'active':''}" aria-pressed="${r===state.role}">${r[0].toUpperCase()+r.slice(1)}</button>`).join('')}</div></header><div class="portal-body"><nav class="sidebar" aria-label="Portal navigation"><small>YOUR WORKSPACE</small>${pages.map(p=>`<button data-action="page" data-value="${p}" class="${state.page===p?'active':''}" aria-current="${state.page===p?'page':'false'}">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</nav><section class="main-content panel-enter">${!staff()?`<div class="row-between" style="margin-bottom:20px"><small>Previewing ${state.role==='parent'?'family of':'student'}:</small>${picker(pupil().name,state.students.map(s=>s.name),'select-pupil')}</div>`:''}${content()}</section></div></div>`;updateSettings()}
function updateSettings(){document.querySelectorAll('[data-style-choice]').forEach(b=>{b.classList.toggle('active',b.dataset.styleChoice===state.style);b.setAttribute('aria-pressed',String(b.dataset.styleChoice===state.style))});document.querySelectorAll('[data-colour]').forEach(b=>b.classList.toggle('active',b.dataset.colour===state.colour));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode))}
function modal(body){$('#task-dialog').innerHTML=body;$('#task-dialog').showModal()}
const dialogFoot='<div class="actions"><button class="primary" type="submit">Save</button><button type="button" data-action="close-modal">Cancel</button></div>';
function studentDialog(){modal(`<form id="student-form"><h2>Welcome a sample pupil.</h2><p class="hint">Fictional names only. No personal contact details needed.</p><label>Sample pupil name<input name="name" maxlength="70" required></label><label>Sample parent name<input name="parent" maxlength="70" required></label><label>Class name<input name="group" value="Qaidah Foundations" maxlength="70" required></label>${dialogFoot}</form>`)}
function homeworkDialog(){modal(`<form id="homework-form"><h2>A task worth practising.</h2><label>Title<input name="title" maxlength="100" required></label><label>Practice instructions<textarea name="text" rows="4" maxlength="1000" required></textarea></label><label>Due date<input name="due" type="date" required value="2026-10-12"></label><p>Class</p><input name="group" type="hidden" value="${esc(pupil().group)}">${picker(pupil().group,[...new Set(state.students.map(s=>s.group))],'homework-group')}${dialogFoot}</form>`)}
function csvParse(text){let rows=[],row=[],field='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field=''}else field+=c}if(quoted)throw Error('A quoted field is unfinished.');row.push(field);if(row.some(Boolean))rows.push(row);return rows}
async function exportView(){try{const css=await fetch('studio.css?v=1').then(r=>{if(!r.ok)throw Error();return r.text()});const clone=$('#workspace').cloneNode(true);clone.querySelectorAll('button').forEach(b=>{b.disabled=true;b.removeAttribute('data-action')});clone.querySelectorAll('details').forEach(d=>d.removeAttribute('open'));const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(state.brand)+' — portal preview</title><style>'+css.replace(/@font-face\{[^}]+\}/,'')+'</style><body data-style="'+state.style+'" style="--accent:'+state.colour+';--tint:'+state.colour+'12"><div class="demo-ribbon">READ-ONLY DESIGN PREVIEW · NOT A LIVE PORTAL · FICTIONAL RECORDS</div>'+clone.outerHTML+'<p style="text-align:center">Prepared with Madrasa Desk · '+esc(state.domain)+' is an illustrative domain only.</p></body></html>';download(html,'madrasa-portal-preview.html','text/html');toast('Your read-only HTML preview has been exported.')}catch(e){toast('Export failed. Please try again while connected.')}}
function download(data,name,type){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.styleChoice){state.style=b.dataset.styleChoice;render()}if(b.dataset.colour){state.colour=b.dataset.colour;render()}if(b.dataset.mode){state.mode=b.dataset.mode;if(state.mode==='solo'&&state.role==='admin')state.role='teacher';render()}const a=b.dataset.action,id=b.dataset.id,v=b.dataset.value;if(!a)return;
if(a==='page'){state.page=v;render()}if(a==='role'){state.role=v;state.page='overview';render();toast('Sample '+v+' view. No real login has been created.')}
if(a==='select-pupil'){state.selected=state.students.find(s=>s.name===v).id;render()}
if(a==='preview-pupil'){state.selected=id;state.role='student';state.page='overview';render()}
if(a==='attendance'){const s=state.students.find(s=>s.id===id);s.attendance=v;log(s.name+': '+v);render()}
if(a==='all-present'){state.students.forEach(s=>s.attendance='Present');log('All sample pupils marked present.');render()}
if(a==='points'){const s=state.students.find(s=>s.id===id);s.points+=5;log('5 points awarded to '+s.name+'.');render()}
if(a==='complete'){const h=state.homework.find(h=>h.id===id);if(!h.done.includes(state.selected))h.done.push(state.selected);log('Practice marked complete.');render()}
if(a==='homework-group'){const form=$('#homework-form');form.querySelector('[name=group]').value=v;const d=b.closest('details');d.querySelector('summary').textContent=v;d.open=false;}
if(a==='student-dialog')studentDialog();if(a==='homework-dialog')homeworkDialog();if(a==='close-modal')$('#task-dialog').close();if(a==='export')exportView();
if(a==='import-dialog')modal('<h2>Try a sample import.</h2><p>Use fictional records only. Your file is read in this browser tab and is not uploaded.</p><p class="hint">CSV columns: name,parent,class. Up to 30 rows; 30 KB maximum. Import adds pupils to this demo.</p><button data-action="csv-template">Download sample CSV</button><form id="import-form"><label>Sample CSV<input type="file" name="csv" accept=".csv,text/csv" required></label>'+dialogFoot+'</form>');
if(a==='csv-template')download('name,parent,class\nZayd Sample,Parent Sample,Qaidah Foundations\nHana Example,Guardian Example,Qur’an Reading\n','sample-pupils.csv','text/csv')});
document.addEventListener('submit',async e=>{if(!['student-form','homework-form','import-form'].includes(e.target.id))return;e.preventDefault();const f=new FormData(e.target),v=Object.fromEntries(f);if(e.target.id==='student-form'){if(![v.name,v.parent,v.group].every(s=>s.trim()))return;state.students.push({id:crypto.randomUUID(),name:v.name.trim(),parent:v.parent.trim(),group:v.group.trim(),attendance:'Not recorded',points:0});log('Sample pupil added.');state.page='students'}if(e.target.id==='homework-form'){if(!state.students.some(s=>s.group===v.group)){toast('Choose a class already in your sample portal.');return}state.homework.push({...v,id:crypto.randomUUID(),done:[]});log('Homework assigned to '+v.group+'.');state.page='homework'}if(e.target.id==='import-form'){try{const file=v.csv;if(file.size>30000)throw Error('Please use a CSV smaller than 30 KB.');const rows=csvParse((await file.text()).replace(/^\uFEFF/,''));if(rows.shift()?.map(x=>x.trim().toLowerCase()).join(',')!=='name,parent,class')throw Error('Use the columns name,parent,class.');if(!rows.length||rows.length>30)throw Error('Use between 1 and 30 sample pupils.');if(rows.some(r=>r.length!==3||r.some(v=>!v.trim()||v.length>70)))throw Error('Each row needs three fields, up to 70 characters each.');rows.forEach(([name,parent,group])=>state.students.push({id:crypto.randomUUID(),name:name.trim(),parent:parent.trim(),group:group.trim(),attendance:'Not recorded',points:0}));log(rows.length+' sample pupils imported.');state.page='students'}catch(err){toast(err.message);return}}$('#task-dialog').close();render()});
$('#customise').onclick=()=>{$('#settings').hidden=false;$('#brand-name').focus()};$('#close-settings').onclick=()=>{$('#settings').hidden=true;$('#customise').focus()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#settings').hidden){$('#settings').hidden=true;$('#customise').focus()}});$('#export').onclick=exportView;$('#start').onclick=()=>{$('#welcome').close();$('#customise').focus()};$('#brand-name').oninput=e=>{state.brand=e.target.value.trim()||'Your madrasa';render()};$('#brand-domain').oninput=e=>{state.domain=e.target.value.trim()||'portal.yourname.co.uk';render()};$('#reset').onclick=()=>{modal('<h2>Reset sample records?</h2><p>This clears the pupils and homework you added in this tab. Your branding stays.</p><div class="actions"><button id="confirm-reset" class="primary">Reset records</button><button data-action="close-modal">Keep my changes</button></div>');$('#confirm-reset').onclick=()=>{samples();state.page='overview';$('#task-dialog').close();render();toast('Sample records reset.')}};
$('#colours').innerHTML=['#395ea5','#34735f','#765aa3','#975c37'].map((c,i)=>`<button data-colour="${c}" style="background:${c}" aria-label="${['Blue','Green','Purple','Terracotta'][i]}"></button>`).join('');$('#styles').innerHTML=styles.map(([id,name,desc])=>`<button data-style-choice="${id}"><strong>${name}</strong><small>${desc}</small></button>`).join('');$('#welcome-styles').innerHTML=styles.map(([id,name,desc])=>`<button class="style-option" data-style-choice="${id}"><div class="mini-layout ${id}" aria-hidden="true"><i></i><i></i></div><div><strong>${name}</strong><p>${desc}</p></div></button>`).join('');samples();render();$('#welcome').showModal();
